# Use an official Node image to build the app
FROM node:20 AS build

# Set working directory
WORKDIR /app

# Copy dependencies and install
COPY package*.json ./
RUN npm install

# Copy the rest and build
COPY . .
RUN npm run build

# Use Nginx to serve the built app
FROM nginx:stable-alpine

# Remove default static files
RUN rm -rf /usr/share/nginx/html/*

# Copy build files from previous stage
COPY --from=build /app/dist /usr/share/nginx/html

# Copy custom Nginx config if you have one (optional)
# COPY nginx.conf /etc/nginx/nginx.conf

# Expose port and run
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]



#"After building the React app using Vite, we get static assets (HTML, JS, CSS). Using npm run dev is not safe for production — it's slow, insecure, and not optimized for performance. That’s why we use Nginx, which is a high-performance web server.
#Nginx serves static files quickly and efficiently, handles compression, supports caching, and can also act as a reverse proxy if needed. It's the industry standard for serving frontend apps in production — like how Facebook, Netflix, and GitHub use it under the hood."