name: CI Pipeline

on:
  push:
    branches: [main]

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    # Step 1: SonarCloud Scan
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@v2
      with:
        projectBaseDir: .
        sonar.organization: priyanshujains
        sonar.projectKey: priyanshujains_Domain-Mapping
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}


    # Step 2: OWASP Dependency-Check
    # - name: Run OWASP Dependency-Check
    #   uses: dependency-check/Dependency-Check_Action@v2
    #   with:
    #     project: 'My Project'
    #     format: 'ALL'
    #     out: 'reports'

    # - name: Upload OWASP report
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: owasp-report
    #     path: reports

    # Step 3: Build Docker Image
    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/secure-app:latest frontend/message-app/

    # Step 4: Trivy Scan
    - name: Run Trivy scan on image
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: '${{ secrets.DOCKER_USERNAME }}/secure-app:latest'
        format: 'table'
        exit-code: '1'
        ignore-unfixed: true
        vuln-type: 'os,library'

    # Step 5: DockerHub login and push
    - name: Login to DockerHub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Push Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/secure-app:latest
